name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- THIS IS THE NEW DEBUGGING STEP ---
      - name: List files in repository
        run: ls -R
      # --------------------------------------

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/453734132373/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer@barlowailabs.iam.gserviceaccount.com'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting,functions --project barlowailabs --non-interactive